### ISSUE TITLE
[Idea] automatic generation of config file

### ISSUE THREAD

**Issue by arves100** [REONTeam/libmobile#1]
Already implemented in the mgba qt fork but feeling that it shouldn't stay there only.

Implenting an automatic generation of the config file would skip the initial trainer process (which comes handy for emulators as it doesn't require an extra rom or step), it would allow to expose dns data and possibly patch the email domain if necessary automatically.

Implementing this might also mean breaking the configuration write operations (expect for byte 0x02 required by Mobile Trainer) which wouldn't be consider to be 1:1 implementation of the adapter (no game should be affected by this I suppose)

Would it benefit libmobile to have such change from an original adapter implementation?

**Comment by InternalLoss** [comment]
> I'm not sure how most other games work yet, so idk to what extent they can be made "plug and play ready" by generating a config, especially if they need an account or whatnot

it seemed like mobile golf spat an error if there was no config, so I assume other games might do this

also, email domain patching is no longer required :)

**Comment by arves100** [comment]
As far as I remember Crystal do need a valid configuration for news data and so on, I haven't checked with mariokart actually so I might be wrong.
If the games do actually need an already validaded account,

**Comment by InternalLoss** [comment]
REON doesn't currently support auto-registration and I don't think there'd be an easy way *to* support that; a generic config would be fine for downloading news, but would fail authentication on GTS/email (though that would be fine!)

**Comment by arves100** [comment]
hmmm then it might make sense to ask people to run the initial configuration like the original adapter does? A config viewer would be handy for an information screen, if there's no need for domain patching and so on then I don't think a config editor would be required? (Only dns editing)

**Comment by mid-kid** [comment]
DNS overriding has been implemented for a while now, solving this particular issue. Config editing will eventually be a thing, but will not be required for initial configuration.
